
Algoritmo Exercicio1
Var
   nota1, nota2, nota3, nota4, nota5 : real
   soma, media : real
Inicio
   Escreva("Digite a 1 nota do aluno: ")
   Leia(nota1)
   Escreva("Digite a 2 nota do aluno: ")
   Leia(nota2)
   Escreva("Digite a 3 nota do aluno: ")
   Leia(nota3)
   Escreva("Digite a 4 nota do aluno: ")
   Leia(nota4)
   Escreva("Digite a 5 nota do aluno: ")
   Leia(nota5)

   soma <- nota1 + nota2 + nota3 + nota4 + nota5
   media <- soma / 5

   Escreva("Media é: ", media)
Fimalgoritmo
